### ISSUE TITLE
Share the shellscript for someone who wants to convert them into the KITTI format 

### ISSUE THREAD

**Issue by LimHyungTae** [rvp-group/vbr-devkit#5]
Hello, above all things, thanks for sharing wonderful datasets.

But as far as I understand, do we need to convert the bag to the KITTI format like that?

```
scene=$1
scene_nums=("00" "01" "02" "03" "04")

for scene_num in ${scene_nums[@]}
do
    echo "${scene}/${scene}_${scene_num}.bag"
    echo "./${scene}_${scene_num}_kitti"
    vbr convert kitti ./${scene}/${scene}_${scene_num}.bag ./${scene}_${scene_num}_kitti
    rm -rf ./${scene}_${scene_num}_kitti/camera_left
    rm -rf ./${scene}_${scene_num}_kitti/camera_right
done 
```

Could you share some ideas on converting bags into a single sequence? I really appreciate any help you can provide.

**Comment by LeoBrizi** [comment]
Hi Lim, thanks for your interest.

You don't need to loop over each bag file, you can convert all the bags of a sequence at once to KITTI format by simply calling:
`vbr convert KITTI input_dir output_dir`
The `input_dir` is the base directory of the dataset sequence, and the `output_dir` is a new directory to save the sequence in the KITTI format.
For example:
`vbr convert kitti ./scene/scene_{train|test} ./scene/scene_{train|test}_kitti`

Let us know if you have any other issues

**Comment by LimHyungTae** [comment]
Oh amazing, and sorry for about this question. I had to RTFM. 

Everything's clear! Thanks.

**Comment by LeoBrizi** [comment]
@bakuljangley yep, the script combines all the rosbags in the input directory.
The script uses AnyReader from rosbags.Highlevel, anyreader garantees the indexing of the messages. From the doc of rosbags: 

> Instances of the [AnyReader](https://ternaris.gitlab.io/rosbags/api/rosbags.highlevel.html#rosbags.highlevel.AnyReader) class give unified access to a list of either ROS1 or ROS2 bag files, but not a mixture of both, and will replay messages in correct timestamp order as if the messages came from a single bag.
