### ISSUE TITLE
[Suggestion] Forcibly setting float32 for preventing unexpected cases

### ISSUE THREAD

**Issue by LimHyungTae** [rvp-group/vbr-devkit#6]
Hello there, now I'm using this wonderful devkit by changing some parts, 

and I'd like to recommend you to change this line:

https://github.com/rvp-group/vbr-devkit/blob/0445515facb005623b2aa34968334ad35b551ccf/python/vbr_devkit/datasets/kitti.py#L85

to this: 

```
clip_points.astype('float32').tofile(dest_path)
```

When I changed some lines, the `clip_points` were unexpectedly changed to float64; thus, by fixing its type, I believe we can prevent some undesirable errors.

**Comment by EmanueleGiacomini** [comment]
Thanks!
We added your suggestion to b422314
