### ISSUE TITLE
How to read the 6-DoF pose for visual odometry

### ISSUE THREAD

**Issue by aofrancani** [rvp-group/vbr-devkit#8]
Hey, congrats on your work, this dataset looks good and well structured. Tks for sharing :)

I'm working with visual odometry algorithms, and it would be nice to have somehow the 6DoF information. The KITTI odometry dataset provides the ground truth as an N x 12 table, represented by the 3x4 transformation matrix ([R t]). Is there a way that I can read your ground truth like this? If so, where can I get this information? 

Just showing me where I can find the position and orientation of each image frame would be helpful and greatly appreciated.

Cheers!

**Comment by EmanueleGiacomini** [comment]
Hi!
First, thanks for your interest :smile:
While downloading a particular training sequence, you should be downloading two files following this convention: `<sequence>_gt.txt` and `vbr_calib.yaml.`

For instance, downloading `campus_train0` will provide you with the `campus_train0_gt.txt` trajectory file.
This file stores the ground truth poses of the LiDAR sensor mounted on our recording rig. 
The `vbr_calib.yaml` file contains the relative pose of the cameras to the LiDAR.

Using these resources, you can obtain the trajectory of your sensor of interest by post-multiplicating the ground truth posed by the relative pose between the sensors.
i.e., if we want to compute the GT for `camera_left`, we do it as follows:
```
world_T_camL = world_T_lidar @ lidar_T_camL 
```

The structure of the calibration yaml is described [here](https://rvp-group.net/slam-dataset.html)

PS: Bear in mind that for GT trajectory, we follow the <x, y, z, qx, qy, qz, qw> convention, while some libraries (i.e., `pytransform3d`) use <x, y, z, qw, qx, qy, qz> convention, so be careful with that :eyes:

**Comment by aofrancani** [comment]
Hey, thanks for the quick and complete reply. I'm sorry I didn't notice it before, I've just read your mention "For the training sequences, we provide an accurate 6-dof ground truth". The problem was that I first downloaded the test data and I was looking for the ground truth on this set. My mistake!

That's exactly what I need. Also thanks for the hint about the quaternion convention. 

Cheers!
